### PR TITLE
Improved UI using closures

### PR DESCRIPTION
**Pull request by goergen95**
This PR is bound to be merged towards end of April 2024 as detailed in #240.

### CODE REVIEW

**Comment by goergen95** [comment]
hi @karpfen, I think we should merge this ASAP, so that when people hit the default branch, e.g. via `remotes::install_github("mapme-initiative/mapme.biodiversity")` they install the latest version. Will keep it only on main until end of April, the release it to CRAN. Would you have any objections to that approach?

**Comment by karpfen** [comment]
Hi @goergen95 woah, nice work!
Yes, I think that's a good way to go. I only had a brief glance at the code now, though.
I didn't come across anything major yet, but I'd definitely like to remove all native R pipes for now and replace them with magrittr style pipes.
I've already changed it, just waiting for my local checks to finish before I push it.

**Comment by goergen95** [comment]
In case you want to peek at the rendered online documentation you can download a artifact on the summary page of the pkgdown action (for the current run this is found [here](https://github.com/mapme-initiative/mapme.biodiversity/actions/runs/8551908542?pr=252)).

**Comment by goergen95** [comment]
Found additional note: 
```
Found the following (possibly) invalid URLs:
  URL: https://www.worldwildlife.org/publications/terrestrial-ecoregions-of-the-world
    From: man/teow.Rd
    Status: 403
    Message: Forbidden
```

but that seems to be a false positive.

**Comment by goergen95** [comment]
merging this now so that users landing on GitHub find the new version. This is bound to be sent to CRAN towards end of April.

**Pull request merged**
