### PR TITLE
A few typos tin the Quickstart

### PR DESCRIPTION
**Pull request by fBedecarrats**
Here it is! As I'm testing the package for a specific use involving training, I might get back to you later with further suggestions to make it more accessible. Many thanks!

### CODE REVIEW

**Comment by goergen95** [comment]
Thanks! Would it be ok if you added these commits over at #85 ? This way we can include your changes in one merge. I think you will simply have to add above commits to the review_documentation branch of your fork.

**Comment by fBedecarrats** [comment]
> Thanks! Would it be ok if you added these commits over at #85 ? This way we can include your changes in one merge. I think you will simply have to add above commits to the review_documentation branch of your fork.

Hi, I'm sorry but I don't know how to do this. I'll try and I hope I won't mess up with something.

**Comment by fBedecarrats** [comment]
hmmm. I don't see how to do this. I understand why it is not practical for you that I split the review in 2 PRs (double merge work on your side for minimal modifications), but I don't know how to edit the previous PR to include the comits of this one. Can you tell me how to do it?

**Comment by goergen95** [comment]
yep, I see the trouble. I think the easiest way to go would be to simply add a new commit to your review-documentation branch with the few changes in the Quickstart vignette. It should then show up there and we can merge :)

**Comment by fBedecarrats** [comment]
> yep, I see the trouble. I think the easiest way to go would be to simply add a new commit to your review-documentation branch with the few changes in the Quickstart vignette. It should then show up there and we can merge :)

I thought I did my new commits in this branch, sorry. Let me try to fix this.

**Comment by goergen95** [comment]
I'll close here as these changes are included in #85

**Pull request closed without merging**
