### PR TITLE
fix reading raster tiles with temporal dimensions

### PR DESCRIPTION
**Pull request by goergen95**

### CODE REVIEW

**Comment by goergen95** [comment]
Hi, I this fixes the issue, I think. Would you mind to check? I also tried to make the code more understandable. Maybe let's have a discussion about the assumptions used here?

**Comment by karpfen** [comment]
Sorry, I saw your request too late. I'm testing on my data right now that caused the problem in the first place.

**Comment by goergen95** [comment]
But shouldn't that be covered for with 87b99ba8?

**Comment by karpfen** [comment]
You're right, I'll add it as an issue, I managed to find a reprex now, too.

**Pull request merged**
