### PR TITLE
Example analysis of NASA FIRMS resource

### LINKED ISSUE #159: Create a tutorial with an example on how to use the downloaded ressources for other kinds of analysis and mapping
Background:
Our packages providers a downloader function for a specific AOI from several different sources and stores it locally. Our processing routines however only focus on aggregating these indicators in the AOI. Other analysis such as point pattern are not possible but very interesting for a more general public. Also using the raw data to create maps and better understand the spatial distribution below an aggregated statistic might have a high value. 

Suggestion: 
Create a vignette that shows where data is stored, how it could be used e.g. to create a raster from it showing like  a heatmap and plot the data in an interactive map. 

Example: 
Download point data for an AOI -> create a raster heat map -> plot AOI, heatmap and point data with `mapView`

### PR DESCRIPTION
**Pull request by goergen95**
Closes #159

### CODE REVIEW

**Comment by Jo-Schie** [comment]
I just had a look at the tutorial. Great work @goergen95 . Really cool example. I like the selective read and I also like how you elaborated a good analysis that clearly shows the value added. Than you very much. Should have a look at it @fBedecarrats  and @melvinhlwong  and @karpfen .... see [here](https://mapme-initiative.github.io/mapme.biodiversity/articles/nasa-firms.html)

**Comment by fBedecarrats** [comment]
Hi! I just read and reproduced the example for [an analysis on a specific PA](https://fbedecarrats.github.io/available_data_makay/) I'm interested in (work very much in progress). It is very well done and clear, congratulations!

2 slight suggestions: 

1. On referencing: the fact is focusing on fire data is not mentionned in the vignette title, although it might be one of the appeals of this example (besides the generic fact of using downloaded resources). One solution could be to expand the title (adding "example with fire data" at the end), another would be to make a link to the vignette in the reference entries for [nasa-firms resource](https://mapme-initiative.github.io/mapme.biodiversity/reference/nasa_firms.html) and/or [active_fire_count indicator](https://mapme-initiative.github.io/mapme.biodiversity/reference/active_fire_counts.html).
2. On the map display: I'm not a big fan of drawing maps with ggplot. I find the syntax cluncky. I used tmap in my example, I think that it is more readable.

**Comment by Jo-Schie** [comment]
Hi @fBedecarrats . Your example is also great. Can we link it somewhere in our repository? I was thinking of having a page where we can link several usage examples of the package... like a collection of external tutorials... what do you think @goergen95 ?

**Comment by goergen95** [comment]
Great analysis! Looking forward to see it polished. 
We have ggplot already as an dependency for building vignettes so I decided not to also include tmap.
Linking to it somewhere in the README or a dedicated page in the online documentation is a great idea if @fBedecarrats agrees?

**Comment by fBedecarrats** [comment]
Thanks! It's still work in progress, so I'd rather wait about a month for this one. I also need to properly attribute my borrowings (most of this code is adapted from original snippets by @Jo-Schie and @goergen95).
For now, I'd rather reference:
- https://fbedecarrats.github.io/conservation-deforestation-madagascar/
- https://lenaigmoign.github.io/JUMI_R/
On forests and mangroves respectively. Both are in French though.

**Comment by goergen95** [comment]
Out of curiosity: what were the reasons you chose to use ACLED over UCDP?

**Comment by fBedecarrats** [comment]
> Out of curiosity: what were the reasons you chose to use ACLED over UCDP?

I think that I'll try both. The aim of this workbook is to explore a large range of available data sources for this PA and it will also be an opportunity to cross check the relevance, completeness and accuracy of these sources. The team I work with will do a lot of field work on this PA (including household surveys, anthropological studies, ecological inventories and ad hoc land cover mapping), which will also enable to forge a better opinion about the reliability of these data sources.

**Comment by fBedecarrats** [comment]
> Out of curiosity: what were the reasons you chose to use ACLED over UCDP?

It appears that the scope of UCDP is much more restrictive than ACLED. For Madagascar, UCDP has 47 events registered from 1989 to 2022, while ACLED has 2,079 events registered from 1997 to 2023. See here: https://fbedecarrats.github.io/available_data_makay/#conflicts
I guess that it would be better to follow-up this discussion on #44.

**Pull request merged**
