### PR TITLE
Add Fritz et al. (2022) Drivers of deforestation for tropical forest resource and indicator

### PR DESCRIPTION
**Pull request by goergen95**

### CODE REVIEW

**Comment by Jo-Schie** [comment]
Hi @goergen95 . Does this need checks and testing? Happy to try out a repex. Not sure if we already have a standardized one with input data. Just let me know if I should do something here to approve the changes. We could also include this in an updated threat assessment report @karpfen ...

**Comment by goergen95** [comment]
From the technical side tests are included. I don't know if you require additional testing before merging?

**Comment by Jo-Schie** [comment]
I would suggest we merge this and try it out in the doing. is that okay for you @goergen95

**Comment by fBedecarrats** [comment]
> I would suggest we merge this and try it out in the doing. is that okay for you @goergen95

Great, congrats!

**Comment by goergen95** [comment]
I just changed the processing mode back to asset mode.
I am fine with merging into main, however, if you are really into testing the feature I would ask you to copy the branch and conduct some tests? As indicated before I am planning for the next CRAN release and it would be easier to exclude this feature if it was not already merged.

**Comment by goergen95** [comment]
@Jo-Schie, I prepared a sample script that constructs a random portfolio on global land masses. This script may very well serve as a template for future indicators. It runs successfully on my machine. Maybe someone can confirm and then I will merge?

``` r
# package setup
load_or_install <- function(lib){
  if(!requireNamespace(lib, quietly = TRUE)) install.packages(lib)
  library(lib, character.only = TRUE)
}
libs <- c("sf", "future", "remotes", "progressr", "rnaturalearth")
for(lib in libs) load_or_install(lib)
#> Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE

install_github("mapme-initiative/mapme.biodiversity",
               ref = "148-drivers-of-deforestation",
               upgrade = "never")
#> Skipping install of 'mapme.biodiversity' from a github remote, the SHA1 (ac269141) has not changed since last install.
#>   Use `force = TRUE` to force installation

library(mapme.biodiversity)

# adjust as needed
nworkers <- 4
nsamples <- 1000
buffer_size <- 50000

# sample a global portfolio
sf_use_s2(F)
#> Spherical geometry (s2) switched off
world <- ne_countries(returnclass = "sf") |> st_make_valid()
world <- st_crop(world, xmin = -170.0, ymin = -60.0,
                 xmax = 170.0, ymax = 80.0) |>
  st_make_valid()
#> although coordinates are longitude/latitude, st_intersection assumes that they
#> are planar
#> Warning: attribute variables are assumed to be spatially constant throughout
#> all geometries
sf_use_s2(T)
#> Spherical geometry (s2) switched on

# construct polygons from sample
set.seed(42)
hooks <- st_sample(world, size = nsamples)
hooks <- st_transform(hooks, "EPSG:3857")
polys <- st_buffer(hooks, dist = buffer_size)
polys <- st_transform(polys, "EPSG:4326")
polys <- st_as_sf(polys)
polys$id <- 1:nrow(polys)

# test deforestation indicator
loc <- tempfile()
dir.create(file.path(loc, "tmp"), recursive = TRUE)

port <- init_portfolio(polys, years = 2000:2020,
                       outdir = loc, tmpdir = file.path(loc, "tmp"))
port <- get_resources(port, "fritz_et_al", res_drivers = 100)
#> Starting process to download resource 'fritz_et_al'........

plan(multisession, workers = nworkers)
with_progress({
  port <- suppressWarnings(calc_indicators(port, "deforestation_drivers"))
})
plan(sequential)

print(port)
#> Simple feature collection with 1000 features and 3 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -163.5686 ymin: -54.50398 xmax: 168.775 ymax: 79.64064
#> Geodetic CRS:  WGS 84
#> # A tibble: 1,000 × 4
#>       id assetid deforestation_drivers                                         x
#>    <int>   <int> <list>                                            <POLYGON [°]>
#>  1     1       1 <tibble [1 × 3]>      ((148.6279 60.94579, 148.6273 60.93437, …
#>  2     2       2 <tibble [1 × 3]>      ((-76.90076 43.55152, -76.90137 43.53448…
#>  3     3       3 <tibble [1 × 3]>      ((56.13946 45.62767, 56.13885 45.61123, …
#>  4     4       4 <tibble [10 × 3]>     ((78.42446 10.61468, 78.42385 10.59157, …
#>  5     5       5 <tibble [10 × 3]>     ((21.46369 -0.5116831, 21.46307 -0.53518…
#>  6     6       6 <tibble [1 × 3]>      ((-149.9771 59.57965, -149.9777 59.56775…
#>  7     7       7 <tibble [1 × 3]>      ((-39.56872 68.67954, -39.56934 68.67099…
#>  8     8       8 <tibble [1 × 3]>      ((85.05521 46.11211, 85.05459 46.09581, …
#>  9     9       9 <tibble [1 × 3]>      ((111.4082 33.7135, 111.4076 33.69394, 1…
#> 10    10      10 <tibble [1 × 3]>      ((66.24787 40.91645, 66.24726 40.89868, …
#> # ℹ 990 more rows
```

<sup>Created on 2023-06-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Pull request merged**
