### PR TITLE
Update Global Forest Cover to version 1.11 (2000-2023)

### PR DESCRIPTION
**Pull request by fBedecarrats**
This PR is to use the latest available verison of global forest cover data.

### CODE REVIEW

**Comment by fBedecarrats** [comment]
Adding the corresponding modifications to the documentation.

**Comment by goergen95** [comment]
Hi @fBedecarrats, this looks good but it is missing updating the example data sets. I have this already up and running locally and I would like to add my commit to your branch containing your your original work. For this to work, you would need to allow upstream maintainers to create commits on your fork (find documentation [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork). Would you consider adding this so I can share my changes in this PR?

**Comment by fBedecarrats** [comment]
> Hi @fBedecarrats, this looks good but it is missing updating the example data sets. I have this already up and running locally and I would like to add my commit to your branch containing your original work. For this to work, you would need to allow upstream maintainers to create commits on your fork (find documentation [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)). Would you consider adding this so I can share my changes in this PR?

I don't understand because according to the documentation, a checkbox should appear on the PR to enable such commits, but I don't see this ckeckbox anywhere. Did I do something wrong when generating this PR that impedes me to authorize this.

**Comment by goergen95** [comment]
Hmm,  I am not sure. It should be visible on the right navbar kind of thing. I could imagine that you might have to log in as the `BETSAKA` organization account?

**Comment by fBedecarrats** [comment]
> Sorry that I cannot be of further help to find that option. In the meantime a pushed my changes to a new branch containing your changes in this repo (see #277). We could merge from there if you don't mind?

Sorry, I only foked main and I'm having a hard time to rebase from this new branch. I think that I will use this approach instead. 
git_2x

Hang on a couple of days and I will submit a new PR.

**Comment by goergen95** [comment]
Merged with #277 because the next CRAN release is planned for the end of the week. Thanks!

**Comment by fBedecarrats** [comment]
Thanks!

**Pull request closed without merging**
