### PR TITLE
create download functions

### PR DESCRIPTION
**Pull request by Ohm-Np**
- accessibility
- drought_indicator
- popCount
- ecoregions
- mangrove
- climateVariables
- ESALandCover

### CODE REVIEW

**Comment by goergen95** [comment]
hi! Thanks for the PR. I collect some aspects for each function that should be addressed before merging that we have partly already discussed today. Please also check the new comment from Johannes [here](https://github.com/mapme-initiative/mapme.biodiversity/issues/1#issuecomment-1044552959).

- accessibility: 
  - first argument shall be called x and represents the portfolio object, bbox should be retrieved from that object (see [here](https://github.com/mapme-initiative/mapme.biodiversity/blob/main/R/get_treecover.R))
- drought_indicator:
  - first argument shall be x as an portfolio object, the temporal range shall be automatically derived from the "years" attribute
- popCoint:
  - first argument shall be x as an portfolio object, the temporal range shall be automatically derived from the "years" attribute
- ecoregions:
  -  first argument shall be called x and represents the portfolio object, bbox should be retrieved from that object
- mangrove:
   - first argument shall be called x and represents the portfolio object, the temporal range shall be automatically derived from the "years" attribute
- climateVariables:
  - first argument shall be called x and represents the portfolio object, the temporal range shall be automatically derived from the "years" attribute, however, we will evaluate if we se a different source for the climate variables
- ESALandCover:
  - please check if we could use the [{RCGLS}](https://cran.r-project.org/web/packages/RCGLS/RCGLS.pdf) package instead of a manual download
  - however, first argument shall be called x and represents the portfolio object, the temporal range  and bbox shall be automatically derived from the its attributes

**Comment by Ohm-Np** [comment]
Hi @goergen95, I pushed changes to the functions and also `resources_backlog.R`. Please let me know if it it is fine or need some more updates.

**Comment by goergen95** [comment]
Before merging we need to address the following open issues:
- check and skip existing files in the resource directories
- retry downloads if it fails
- check potential for parallel downloads e.g. via aria2c
- currently downloads for the following resources fail on my machine:
  - climate variables (we may also check for another source e.g. using [CHIRPS](https://docs.ropensci.org/chirps/))
  - srtm
- additionally the api for downloading data from soil grids still has to be implemented by me

**Comment by goergen95** [comment]
The issues stated above have been addressed in the following way:
- all download functions now check if the original downloaded file exists in the output directory. That also means that we do not delete, e.g. zip files. If a file exists the download is skipped
- unsucessfull downloads are logged and retried
- for the time being we do not address parallel downloads. This might be a nice feature in the future
- we stay with the WorldClim variables as these have a monthly resolution which is fine for most use cases (as discussed yesterday)
- srtm downloads now work and we also retry downloads for unsuccessful downloads (see above)
- download functionality for a high number of resources from soil grids have been implemented

**Pull request merged**
