### PR TITLE
Review documentation

### PR DESCRIPTION
**Pull request by fBedecarrats**
As I was reading through the documentation, I found a few typos and proposed corrections enclosed in this PR. Many thanks for this great package!
NB: I have not reviewed the Quickstart yet.

### CODE REVIEW

**Review by Jo-Schie — APPROVED** [review]

**Comment by Jo-Schie** [comment]
very nice. Thanks a lot @fBedecarrats. I am running the necessary checks and will then merge afterwards.

**Comment by goergen95** [comment]
Thanks a lot for improving the documentation!! Do you plan to add your improvements for the Quickstart vignette as well? Besides that, only rending the index.Rmd seems to be missing before we can merge.

**Comment by fBedecarrats** [comment]
Hi @goergen95 , does it work like this?

**Comment by goergen95** [comment]
That looks great! Thanks.

**Review by goergen95 — APPROVED** [review]

**Comment by goergen95** [comment]
Thanks again for the improvements! Please let us know about any further feedback from your workshop as we are very interested in user-feedback.

**Comment by fBedecarrats** [comment]
> Thanks again for the improvements! Please let us know about any further feedback from your workshop as we are very interested in user-feedback.

Many thanks Darius. I'll prepare some feedbacks!

**Pull request merged**
